"""Constants and configuration parameters for Variant 22."""

OP_CREATE_SESSION = 1
OP_DELETE_SESSION = 2
OP_GET_ALL_SESSIONS = 3
OP_UPDATE_SESSION = 4

OP_CREATE_REQUEST = 5
OP_DELETE_REQUEST = 6
OP_GET_ALL_REQUESTS = 7
OP_UPDATE_REQUEST = 8

OP_CREATE_ANSWER = 9
OP_DELETE_ANSWER = 10
OP_GET_ALL_ANSWERS = 11
OP_UPDATE_ANSWER = 12

OP_QUERY_JOIN = 13

REQ_OP_OFFSET = 0
REQ_OP_SIZE = 1
REQ_LEN_OFFSET = 1
REQ_LEN_SIZE = 3
REQ_HEADER_SIZE = 4

RESP_LEN_OFFSET = 0
RESP_LEN_SIZE = 5
RESP_OP_OFFSET = 5
RESP_OP_SIZE = 1
RESP_HEADER_SIZE = 6

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9922
JOURNAL_FILE = "journal.log"

WINDOW_MINUTES = 6
SECONDS_PER_MINUTE = 60
QUERY_TIME_WINDOW_SECONDS = 360

BYTE_ORDER = "big"
ENCODING = "utf-8"

STATUS_SUCCESS = "success"
STATUS_ERROR = "error"

ZERO = 0
ONE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
SEVEN = 7
EIGHT = 8

INDEX_UID = 0
INDEX_TIMESTAMP = 1
INDEX_LOCALE = 2
INDEX_USER_AGENT = 3

INDEX_REQ_CONTENT = 2
INDEX_REQ_SESSION = 3
INDEX_REQ_TRIGGERED = 4

INDEX_ANS_OUTPUT = 2
INDEX_ANS_STATUS = 3
INDEX_ANS_EXCEPTION = 4
INDEX_ANS_REQUEST = 5
INDEX_ANS_CACHE_HIT = 6

REPL_PROMPT = "variant22> "
REPL_EXIT_CMD = "exit"
REPL_HELP_CMD = "help"
